Week-7/W7D2/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :show, :update, :edit, :destroy]

  

end

Week-7/W7D2/music_app/app/models/album.rb
class Album < ApplicationRecord
    belongs_to :band,
        foreign_key: :band_id,
        class_name: :Band

end

Week-7/W7D2/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :albums,
    foreign_key: :band_id,
    class_name: :Album
  
end

Week-7/W7D2/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :session_token, uniqueness: true

  attr_reader :password
  after_initialize :ensure_session_token

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      return nil
    end
  end

end

Week-7/W7D2/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def new
        @band = Band.find_by(band_id: params[:band_id])
        @album = Album.new(band_id: params[:band_id])
        render :new
    end

    def show
        @album = Album.find_by(id: params[:id])
        render :show
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def edit
        @album = Album.find_by(id: params[:id])
        render :edit
    end

    def update
        @album = Album.find_by(id: params[:id])
        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :edit
        end
    end

    def destroy
        @album = Album.find_by(id: params[:id])
        @album.destroy
        redirect_to albums_url
    end

    private
    def album_params
        params.require(:album).permit(:title, :year, :live, :band_id)
    end
end

Week-7/W7D2/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
       @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end
    
    def login_user!(user)
        session[:session_token] = user.reset_session_token!
    end
end

Week-7/W7D2/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def show
    @band = Band.find_by(id: params[:id])
    render :show
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  
  def band_params
    params.require(:band).permit(:name)
  end

end

Week-7/W7D2/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )
        if user
            login_user!(user) #write this later
            #debugger
            redirect_to user_url(user)#write this later
        else
            flash[:errors] = ["invalid credentials"]
            redirect_to new_session_url
        end
    end

    def destroy
        # user = User.find_by(params: params[:id])
        # user.destroy
        # render :

        current_user.reset_session_token!
        session[:session_token] = nil 
        redirect_to new_session_url
    end
end

Week-7/W7D2/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def create
        @user = User.new(user_params)
        if @user.save!
            login_user!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def new
        @user = User.new
        render :new
    end

    def show
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

Week-7/W7D2/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

Week-7/W7D2/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

Week-7/W7D2/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

Week-7/W7D2/music_app/app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>

<form action="<%=action_url%>" method="POST">
<input type="hidden" name="_method" value="<%=http_method%>">
<input 
  type="hidden" 
  name="authenticity_token" 
  value="<%=form_authenticity_token%>">
  <label>Album Name</label>
  <input type="text" name="album[name]" value="<%=band.name%>">


<!--
drop down of which band recorded
    1. label for band names
    2. iterate thru your column of 
    band names and put each one as an option
-->
    <label>Band Name</label>
    <select name="album[band_id]">
        <%Band.all.each do |band|%>
        <option value="<%= band.id %>">
                <%= band.name %>
        </option>
        <%end%>
    </select>

<!--
regular input year,

radio live or not live
  -->






  <input type="submit">


</form>

Week-7/W7D2/music_app/app/views/albums/show.html.erb
<h1> <%= @album.name%> </h1>
<p>
<%= @album.year%>

</p>

Week-7/W7D2/music_app/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form action="<%=action_url%>" method="POST">
<input type="hidden" name="_method" value="<%=http_method%>">
<input 
  type="hidden" 
  name="authenticity_token" 
  value="<%=form_authenticity_token%>">
  <label>Band Name</label>
  <input type="text" name="band[name]" value="<%=band.name%>">
  <input type="submit">


</form>

Week-7/W7D2/music_app/app/views/bands/edit.html.erb
<h1> E D I T </h1>
<h2><%=@band.name%></h2>

<%= render  "form", band: @band %>

Week-7/W7D2/music_app/app/views/bands/index.html.erb
<h1> B A N D S </h1>
<ul>

  <% @bands.each do |band| %>
  <li> <a href="<%= band_url(band) %>"> <%= band.name %> </a> </li>
  <% end %>
</ul>

Week-7/W7D2/music_app/app/views/bands/new.html.erb
<h1> N E W  B A N D  S I G N U P </h1>

<%= render  "form", band: @band %>

Week-7/W7D2/music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

Week-7/W7D2/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THE BEST MUSIC APP EVER INVENTED</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <h2>WELCOME TO OUR AWESOME MUSIC SITE, <%= current_user.email %>!</h2>
        <form action=<%=session_url %> method="POST">
          <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="DELETE">
          <input type="submit" value="LOGOUT">
        </form>
    <% else %>
      <a href=<%= new_user_url %>>SIGN UP!</a>
      <a href=<%= new_session_url %>>SIGN IN!!</a>
    <% end %>
    <%= yield %>
  </body>
</html>

Week-7/W7D2/music_app/app/views/users/new.html.erb
<h1>NEW USER</h1>


<form action="<%=users_url%>" method="POST">
<input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <label>Email</label>
    <input type="text" name="user[email]" value="<%= @user.email %>">
    
  <br>
    <label>Password</label>
    <input type="password" name="user[password]">
    
  <br>
  <input type="submit" value="SIGN UP HERE!">
</form>


  

Week-7/W7D2/music_app/app/views/users/show.html.erb
<h1>USER PROFILE</h1>

<p>
  Email: <%= current_user.email%>
</p>